foreach(comp ${xxx_FIND_COMPONENTS})
        message(STATUS "Looking for component ${comp} in ${CMAKE_CURRENT_LIST_DIR}")
        include("${CMAKE_CURRENT_LIST_DIR}/${comp}Config.cmake")
        if(TARGET xxx::${comp})
            message(STATUS "xxx::${comp} was FOUND")
        else()
            message(STATUS "xxx::${comp} was not FOUND")
        endif()
endforeach(comp foo bar)